version: '3'

services:
  banco-django:
    image: postgres:12.6
    container_name: banco-django
    restart: unless-stopped
    environment:
      POSTGRES_DB: backlog-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    networks:
          - aula-network

  lccvbacklog:
        container_name: lccvbacklog
        restart: unless-stopped
        environment:
          DJANGO_SETTINGS_MODULE: 'desafio.settings'
        build: 
          context: back_end
          dockerfile: ../Dockerfile
    
        command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
          - ./back_end:/code
        ports:
          - "8000:8000"
        depends_on:
          - banco-django
        networks:
          - aula-network

networks:
  aula-network:
    driver: bridge