# Generated by Django 4.0 on 2021-12-10 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=60)),
                ('cnpj', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='NaturezasDespesa',
            fields=[
                ('id_natureza_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('cod_natureza_despesas', models.CharField(max_length=8)),
                ('desc_natureza_despesa', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Naturezas Despesas',
            },
        ),
        migrations.CreateModel(
            name='Notas_fiscais',
            fields=[
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_nota_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('id_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notas_fiscais', to='patrimonio.fornecedores')),
                ('id_natureza_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notas_fiscais', to='patrimonio.naturezasdespesa')),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=80)),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='ItensNotaFiscal',
            fields=[
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_item_nota_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('valor_unitario', models.FloatField()),
                ('vinculado', models.BooleanField(default=False)),
                ('id_nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItensNotaFiscal', to='patrimonio.notas_fiscais')),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bens',
            fields=[
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_bem', models.AutoField(primary_key=True, serialize=False)),
                ('tombamento', models.CharField(max_length=10)),
                ('id_estado_bem', models.IntegerField()),
                ('id_situacao_uso_bem', models.IntegerField()),
                ('valor_aquisicao', models.IntegerField()),
                ('id_marca', models.IntegerField()),
                ('dt_lim_garantia', models.DateField()),
                ('id_nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bens', to='patrimonio.notas_fiscais')),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
