# Generated by Django 4.0 on 2021-12-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bens',
            options={'verbose_name_plural': 'Bens'},
        ),
        migrations.AlterModelOptions(
            name='itensnotafiscal',
            options={'verbose_name_plural': 'Itens Notas Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='notas_fiscais',
            options={'verbose_name_plural': 'Notas Fiscais'},
        ),
    ]
