# Generated by Django 4.0 on 2021-12-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_alter_bens_options_alter_itensnotafiscal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBem',
            fields=[
                ('id_estado_bem', models.AutoField(primary_key=True, serialize=False)),
                ('estado_bem', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Estado bem',
            },
        ),
        migrations.CreateModel(
            name='SituacoesUsoBem',
            fields=[
                ('id_situacao_uso_bem', models.AutoField(primary_key=True, serialize=False)),
                ('situacao_uso_bem', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Situacoes uso bem',
            },
        ),
        migrations.AlterField(
            model_name='bens',
            name='valor_aquisicao',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bens',
            name='id_estado_bem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bens', to='patrimonio.estadobem'),
        ),
        migrations.AlterField(
            model_name='bens',
            name='id_situacao_uso_bem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bens', to='patrimonio.situacoesusobem'),
        ),
    ]
