# Generated by Django 3.2.7 on 2021-12-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0005_alter_bens_id_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas_fiscais',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
