# Generated by Django 3.2.7 on 2021-12-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_alter_notas_fiscais_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bens',
            options={'ordering': ['id_bem'], 'verbose_name_plural': 'Bens'},
        ),
        migrations.AlterModelOptions(
            name='estadobem',
            options={'ordering': ['estado_bem'], 'verbose_name_plural': 'Estado bem'},
        ),
        migrations.AlterModelOptions(
            name='fornecedores',
            options={'ordering': ['razao_social'], 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='itensnotafiscal',
            options={'ordering': ['id_item_nota_fiscal'], 'verbose_name_plural': 'Itens Notas Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='marcas',
            options={'ordering': ['marca'], 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='naturezasdespesa',
            options={'ordering': ['cod_natureza_despesas'], 'verbose_name_plural': 'Naturezas Despesas'},
        ),
        migrations.AlterModelOptions(
            name='notas_fiscais',
            options={'ordering': ['id_nota_fiscal'], 'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='situacoesusobem',
            options={'ordering': ['situacao_uso_bem'], 'verbose_name_plural': 'Situacoes uso bem'},
        ),
        migrations.AddField(
            model_name='bens',
            name='dt_inicio_uso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bens',
            name='observacao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='bens',
            table='Bens',
        ),
        migrations.AlterModelTable(
            name='estadobem',
            table='EstadoBem',
        ),
        migrations.AlterModelTable(
            name='fornecedores',
            table='Fornecedores',
        ),
        migrations.AlterModelTable(
            name='itensnotafiscal',
            table='ItensNotaFiscal',
        ),
        migrations.AlterModelTable(
            name='marcas',
            table='Marcas',
        ),
        migrations.AlterModelTable(
            name='naturezasdespesa',
            table='NaturezasDespesas',
        ),
        migrations.AlterModelTable(
            name='notas_fiscais',
            table='NotasFiscais',
        ),
        migrations.AlterModelTable(
            name='situacoesusobem',
            table='SituacoesUsoBem',
        ),
    ]
