# Generated by Django 3.2.7 on 2021-12-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0007_auto_20211211_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bens',
            name='observacao',
        ),
        migrations.AddField(
            model_name='bens',
            name='observacoes',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
