# Generated by Django 3.2.7 on 2021-12-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0008_auto_20211211_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bens',
            name='dt_fim_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bens',
            name='dt_inicio_uso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bens',
            name='dt_lim_garantia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
