# Generated by Django 3.2.7 on 2021-12-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0009_auto_20211211_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacoesusobem',
            name='situacao_uso_bem',
            field=models.CharField(choices=[('Em uso', 'Em uso'), ('Em cautela', 'Em cautela'), ('Em manutencao', 'Em manutencao'), ('Em disponibilidade', 'Em disponibilidade'), ('Aguardando recolhimento', 'Aguardando recolhimento'), ('Recolhido', 'Recolhido')], max_length=80),
        ),
    ]
